experiment_name: tune_cafodfa_mnist_cnn_3block
algorithm:
  name: CaFo
data:
  name: MNIST
  root: ./data
  val_split: 0.1
  num_classes: 10
  input_channels: 1
  image_size: 28
data_loader:
  batch_size: 128
  num_workers: 0
  pin_memory: false
model:
  name: CaFo_CNN
  params:
    block_channels:
    - 32
    - 128
    - 512
    activation: ReLU
    use_batchnorm: true
    kernel_size: 3
    pool_kernel_size: 2
    pool_stride: 2
algorithm_params:
  train_blocks: true
  block_training_epochs: 5
  block_optimizer_type: Adam
  block_lr: 0.0004977965859721583
  block_weight_decay: 9.594431243311431e-07
  predictor_optimizer_type: Adam
  predictor_lr: 0.00025391813833013565
  predictor_weight_decay: 2.0840357948896564e-06
  loss_type: CrossEntropyLoss
  num_epochs_per_block: 12
  log_interval: 9999
  aggregation_method: sum
logging:
  level: INFO
  wandb:
    use_wandb: false
checkpointing:
  checkpoint_dir: null
monitoring:
  enabled: false
  energy_enabled: false
profiling:
  enabled: false
tuning:
  enabled: true
  n_trials: 50
  direction: maximize
  metric: val_accuracy
  sampler: TPE
  pruner: None
  cafo_predictor_lr_range:
  - 0.0002
  - 0.005
  cafo_predictor_wd_range:
  - 1.0e-07
  - 0.0001
  cafo_epochs_per_block_range:
  - 3
  - 15
  cafo_block_lr_range:
  - 2.0e-05
  - 0.0005
  cafo_block_wd_range:
  - 1.0e-07
  - 0.0001
