experiment_name: "tune_mf_cifar100_mlp_3x2000"
algorithm:
  name: "MF"

data:
  name: "CIFAR100"
  root: "./data"
  val_split: 0.1
  num_classes: 100
  input_channels: 3
  image_size: 32

data_loader:
  batch_size: 128
  num_workers: 0
  pin_memory: false

model:
  name: "MF_MLP"
  params:
    hidden_dims: [2000, 2000, 2000]
    activation: "ReLU"
    bias: true

algorithm_params:
  optimizer_type: "Adam"
  lr: 0.00017277890583771544
  weight_decay: 0.0
  epochs_per_layer: 30
  log_interval: 9999

logging:
  level: "INFO"
  wandb:
    use_wandb: false

checkpointing:
  checkpoint_dir: null

monitoring:
  enabled: false
  energy_enabled: false
profiling:
  enabled: false

tuning:
  enabled: true
  n_trials: 50
  direction: "maximize"
  metric: "val_accuracy"
  sampler: "TPE"
  pruner: "None"
  mf_lr_range: [1.0e-5, 1.0e-2]
  mf_epochs_per_layer_range: [5, 30]