experiment_name: mf_joint_cifar100_mlp_3x2000
algorithm:
  name: MF_JOINT

data:
  name: CIFAR100
  root: "./data"
  val_split: 0.1
  num_classes: 100
  input_channels: 3
  image_size: 32

data_loader:
  batch_size: 128
  num_workers: 4
  pin_memory: true

model:
  name: "MF_MLP"
  params:
    hidden_dims: [2000, 2000, 2000]
    activation: "ReLU"
    bias: true

optimizer:
  type: "Adam"
  lr: 0.00010444918318653514
  weight_decay: 0.0008334433123035028

algorithm_params:
  aux_weight: 1.6908131225459286
  log_interval: 9999

logging:
  level: "INFO"
  wandb:
    use_wandb: true

checkpointing:
  checkpoint_dir: null

monitoring:
  enabled: true
  energy_enabled: true
  energy_interval_sec: 0.2
profiling:
  enabled: true
  verbose: false
