# File: configs/mf/cifar100_cnn_4layer.yaml
experiment_name: "mf_cifar100_cnn_4layer"
algorithm: { name: "MF" }
data: { name: "CIFAR100", root: "./data", val_split: 0.1, num_classes: 100, input_channels: 3, image_size: 32 }
data_loader: { batch_size: 128, num_workers: 4, pin_memory: true }
model: { name: "MF_CNN", params: { activation: "ReLU", bias: true } }
algorithm_params:
  optimizer_type: Adam
  lr: 8.468008575248323e-05
  weight_decay: 0.0
  epochs_per_layer: 58
  log_interval: 9999
  mf_early_stopping_enabled: true
  mf_early_stopping_patience: 20
  mf_early_stopping_min_delta: 0.0001
logging: { level: "INFO", wandb: { use_wandb: true } }
checkpointing: { checkpoint_dir: "checkpoints/mf_cifar100_cnn_4layer" }
monitoring: { enabled: true, energy_enabled: true, energy_interval_sec: 0.2 }
profiling: { enabled: true, verbose: false }