experiment_name: bp_ds_fashion_mnist_mlp_2x1000
algorithm:
  name: BP_DS

data:
  name: FashionMNIST
  root: "./data"
  val_split: 0.1
  num_classes: 10
  input_channels: 1
  image_size: 28

data_loader:
  batch_size: 128
  num_workers: 4
  pin_memory: true

model:
  name: "MF_MLP"
  params:
    hidden_dims: [1000, 1000]
    activation: "ReLU"
    bias: true

optimizer:
  type: "AdamW"
  lr: 0.00017945862639137368
  weight_decay: 0.0005018409836668524

algorithm_params:
  aux_weight: 0.09502449430354566
  log_interval: 9999

logging:
  level: "INFO"
  wandb:
    use_wandb: true

checkpointing:
  checkpoint_dir: null

monitoring:
  enabled: true
  energy_enabled: true
  energy_interval_sec: 0.2
profiling:
  enabled: true
  verbose: false
